### ISSUE TITLE
Receiver not registered: net.pubnative.lite.sdk.receiver.VolumeChangedActionReceiver

### ISSUE THREAD

**Issue by KrestM** [pubnative/pubnative-hybid-android-sdk#1]
Hello! We started facing with such error in our logs. Would be great if someone could take a look at this error which seems related to improper unregistration of some broadcast receiver. Thanks!

The version of sdk: 2.11.1

At least I haven't found in release notes that anything similar has been fixed.

```Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: net.pubnative.lite.sdk.receiver.VolumeChangedActionReceiver@b3fb705
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1338)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1583)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:672)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:672)
       at net.pubnative.lite.sdk.vpaid.volumeObserver.VolumeObserver.unregisterMediaButtonReceiver(VolumeObserver.java:62)
       at net.pubnative.lite.sdk.vpaid.volumeObserver.VolumeObserver.unregisterVolumeObserver(VolumeObserver.java:39)
       at net.pubnative.lite.sdk.vpaid.VideoAdControllerVast.destroy(VideoAdControllerVast.java:577)
       at net.pubnative.lite.sdk.vpaid.BaseVideoAdInternal.releaseAdController(BaseVideoAdInternal.java:136)
       at net.pubnative.lite.sdk.vpaid.BaseVideoAd.destroy(BaseVideoAd.java:156)
       at net.pubnative.lite.sdk.vpaid.VideoAd.destroy(VideoAd.java:16)
       at net.pubnative.lite.sdk.banner.presenter.VastAdPresenter.destroy(VastAdPresenter.java:129)
       at net.pubnative.lite.sdk.presenter.AdPresenterDecorator.destroy(AdPresenterDecorator.java:97)
       at net.pubnative.lite.sdk.views.HyBidAdView.cleanup(HyBidAdView.java:319)
       at net.pubnative.lite.sdk.views.HyBidAdView.destroy(HyBidAdView.java:300)

**Comment by eros902002** [comment]
Thanks for the report @KrestM . Closing this one since it has been fixed since version 2.20.0.
