### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by CWftw** [pubnative/pubnative-hybid-android-sdk#3]
Hi,

After adding the Verve Applovin mediation adapter to our project we have begun to see hundreds of crashes related to the PubNative SDK.

build.gradle
`implementation 'com.applovin.mediation:verve-adapter:2.17.0.0'`

crash
`Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5264)
       at android.view.ViewGroup.addView(ViewGroup.java:5093)
       at net.pubnative.lite.sdk.mraid.MRAIDView.closeFromExpanded(MRAIDView.java:1089)
       at net.pubnative.lite.sdk.mraid.MRAIDView.lambda$close$0(MRAIDView.java:644)
       at net.pubnative.lite.sdk.mraid.MRAIDView.$r8$lambda$hwNM5Q6CfOE61dv8TuwvnfXdhiQ(MRAIDView.java)
       at net.pubnative.lite.sdk.mraid.MRAIDView$$InternalSyntheticLambda$1$96e92ac5957ad5a5746405799b7c9a77b042b528b9732d5c3d8bb786261a9f81$0.run(MRAIDView.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8301)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)`

We're not sure if there's any way we can fix this as it looks to be internal to the SDK. Is there something we are doing wrong?

**Comment by eros902002** [comment]
Thanks for the report @CWftw . This issue has been solved since the version 2.20.0 release. Please do reach out if you have any other sort of problems. More than happy to help.
